{% set name = "google-cloud-trace" %}
{% set version = "1.3.1" %}
{% set sha256 = "3f9f73b5277f36c167991dabf6e29110260ae2e2ad87a2ecf106bf9d7875aade" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
  run:
    - python >=3.6
    - google-api-core-grpc >=1.26.0,<2.0.0dev
    - proto-plus >=1.4.0
    - packaging >=14.3

test:
  imports:
    - grpc
    - google.cloud.trace
    - google.cloud.trace_v1
    - google.cloud.trace_v2

about:
  home: https://github.com/googleapis/python-trace
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Stackdriver Trace API client library
  description: "The Stackdriver Trace API sends application trace data to Stackdriver Trace for viewing. Trace data is collected for all App Engine applications by default. Trace data from other applications can be provided using this API.\nSee the [quick start guide](https://googleapis.dev/python/cloudtrace/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/cloudtrace/latest/index.html
  dev_url: https://github.com/googleapis/python-trace

extra:
  recipe-maintainers:
    - parthea
